### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by xiejunyu** [overtrue/php-opencc#1]
Downloading https://packagist.phpcomposer.com/packages.json
[200] https://packagist.phpcomposer.com/packages.json
Writing C:/Users/xjy/AppData/Local/Composer/repo/https---packagist.phpcomposer.com/packages.json into cache
Downloading https://packagist.phpcomposer.com/p2/overtrue/php-opencc.json
[404] https://packagist.phpcomposer.com/p2/overtrue/php-opencc.json
Downloading https://packagist.phpcomposer.com/p2/overtrue/php-opencc~dev.json
[404] https://packagist.phpcomposer.com/p2/overtrue/php-opencc~dev.json
Downloading https://packagist.org/search.json?q=overtrue%2Fphp-opencc&type=
[200] https://packagist.org/search.json?q=overtrue%2Fphp-opencc&type=

In PackageDiscoveryTrait.php line 362:

  [InvalidArgumentException]
  Could not find package overtrue/php-opencc. It was however found via repository search, which indicates a consistency issue with the repository.

**Comment by overtrue** [comment]
你用的源已经停止维护了吧。

xiejunyu ***@***.***>于2023年6月15日 周四17:38写道：
