### ISSUE TITLE
php运行出错，麻烦看看

### ISSUE THREAD

**Issue by lgsky183** [overtrue/php-opencc#2]
你好：我 windows10，php8.1.25  安装了，命令行转换正常。使用php代码出差：
`<?php 
use Overtrue\PHPOpenCC\OpenCC;
echo OpenCC::convert('服务器', 'SIMPLIFIED_TO_TAIWAN_WITH_PHRASE'); 
// output: 伺服器
die();
`
提示错误：**PHP Fatal error:  Uncaught Error: Class "Overtrue\PHPOpenCC\OpenCC" not found** 
麻烦看看是什么问题

![1](https://github.com/overtrue/php-opencc/assets/150876683/4ed5e5a3-3983-48c4-8ad4-e5b56ad8cc62)
![2](https://github.com/overtrue/php-opencc/assets/150876683/2cef2c15-312b-4200-8f98-157b9915e413)
![3](https://github.com/overtrue/php-opencc/assets/150876683/d76a2cfe-1ba0-46bb-bdc5-f8cffb67f38d)

**Comment by overtrue** [comment]
你都没有引入 composer 的 autoload 文件啊……

**Comment by lgsky183** [comment]
我不懂composer的使用！可以了，感谢！
