### ISSUE TITLE
能否支持php7.x

### ISSUE THREAD

**Issue by taksssss** [overtrue/php-opencc#3]
overtrue/php-opencc 1.0.0 requires php >=8.0 which does not match your installed version 7.3.33.

想请教一下，如何修改能支持7.x版本呢？

**Comment by overtrue** [comment]
这个就得你自己一个个去检查看看版本差异了，毕竟 PHP 8.1 都停止开发 8 个月了，8.2 还有 4 个月也进入仅安全修复阶段了。

**Comment by taksssss** [comment]
T T，谢谢。
